#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using IseFrameworkUnitTest;
using System.Runtime.Serialization;


namespace IseFrameworkUnitTest	
{
	[DataContract(Name = "CsCustomerDto")]
	public partial class CsCustomerDto
	{
		private long _customerid;
		[DataMember(Name = "CustomerId", IsRequired = false)]
		public virtual long CustomerId 
		{ 
		    get
		    {
		        return this._customerid;
		    }
		    set
		    {
		        this._customerid = value;
		    }
		}
		
		private string _fname;
		[DataMember(Name = "Fname", IsRequired = false)]
		public virtual string Fname 
		{ 
		    get
		    {
		        return this._fname;
		    }
		    set
		    {
		        this._fname = value;
		    }
		}
		
		private string _phone;
		[DataMember(Name = "Phone", IsRequired = false)]
		public virtual string Phone 
		{ 
		    get
		    {
		        return this._phone;
		    }
		    set
		    {
		        this._phone = value;
		    }
		}
		
		private string _lname;
		[DataMember(Name = "Lname", IsRequired = false)]
		public virtual string Lname 
		{ 
		    get
		    {
		        return this._lname;
		    }
		    set
		    {
		        this._lname = value;
		    }
		}
		
		private long? _id;
		[DataMember(Name = "Id", IsRequired = false)]
		public virtual long? Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private IList<CsOrderDto> _csorders = new List<CsOrderDto>();
		[DataMember(Name = "CsOrders", IsRequired = false)]
		public virtual IList<CsOrderDto> CsOrders 
		{ 
		    get
		    {
		        return this._csorders;
		    }
		    set
		    {
		        this._csorders = value;
		    }
		}
		
	}
}
