#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using IseFrameworkUnitTest;

namespace IseFrameworkUnitTest	
{
	public partial class CsOrder
	{
		private long _orderid;
		public virtual long OrderId
		{
			get
			{
				return this._orderid;
			}
			set
			{
				this._orderid = value;
			}
		}
		
		private long? _amount;
		public virtual long? Amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				this._amount = value;
			}
		}
		
		private DateTime? _orderdate;
		public virtual DateTime? OrderDate
		{
			get
			{
				return this._orderdate;
			}
			set
			{
				this._orderdate = value;
			}
		}
		
		private long? _customerid;
		public virtual long? CustomerId
		{
			get
			{
				return this._customerid;
			}
			set
			{
				this._customerid = value;
			}
		}
		
		private long? _id;
		public virtual long? Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private CsCustomer _cscustomer;
		public virtual CsCustomer Cscustomer
		{
			get
			{
				return this._cscustomer;
			}
			set
			{
				this._cscustomer = value;
			}
		}
		
		private IList<CsOrderitem> _csorderitems = new List<CsOrderitem>();
		public virtual IList<CsOrderitem> CsOrderitems
		{
			get
			{
				return this._csorderitems;
			}
		}
		
	}
}
#pragma warning restore 1591
