#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using IseFrameworkUnitTest;


namespace IseFrameworkUnitTest	
{
	public partial class CsOrderitemRepository : ISE.Framework.Server.Core.DataAccessBase.IRepository<CsOrderitem, CsOrderitemDto>
	{
		private EntitiesModel1 context;
		
		public EntitiesModel1 Context
		{
		    get
		    {
		        if (this.context == null)
		        {
		            this.context = new EntitiesModel1();
		        }
		        return this.context;
		    }
		}
		
		public CsOrderitemDto FindSingle(Expression<Func<CsOrderitem, bool>> expression)
		{
		    if (expression == null)
		    {
		        expression = (x) => true;
		    }
		    CsOrderitem oaObj = this.Context.GetAll<CsOrderitem>().Where(expression).FirstOrDefault();
		
		    return GetDto(oaObj);
		}
		
		public IList<CsOrderitemDto> Find(Expression<Func<CsOrderitem, bool>> expression)
		{
		    if (expression == null)
		    {
		        expression = (x) => true;
		    }
		    IQueryable<CsOrderitem> oaObjects = this.Context.GetAll<CsOrderitem>().Where(expression);
		
		    return GetDtos(oaObjects);
		}
		
		public IQueryable<CsOrderitem> GetQueryable()
		{    
		    IQueryable<CsOrderitem> oaObjects = this.Context.GetAll<CsOrderitem>();
		
		    return oaObjects;
		}
		
		public long Count(Expression<Func<CsOrderitem, bool>> expression)
		{
		    if (expression == null)
		    {
		        expression = (x) => true;
		    }
		   long count = this.Context.GetAll<CsOrderitem>().Count(expression);
		
		    return count;
		}
		
		internal static CsOrderitem CreateInternal(CsOrderitemDto dtObj, EntitiesModel1 context)
		{
			if(dtObj == null)
			{
				return null;
			}
			CsOrderitem oaObj = new CsOrderitem();
		
			oaObj.OrderitemId = dtObj.OrderitemId;
			oaObj.Title = dtObj.Title;
			oaObj.OrderId = dtObj.OrderId;
			oaObj.Id = dtObj.Id;
		
			context.Add(oaObj);
			return oaObj;
		}
		
		public CsOrderitem Create(CsOrderitemDto dtObj)
		{
			return CreateInternal(dtObj, this.Context);
		}
		
		internal static CsOrderitem UpdateOrCreateInternal(CsOrderitemDto dtObj, EntitiesModel1 context)
		{
			if(dtObj == null)
			{
				return null;
			}
			CsOrderitem oaObj = (from t in context.GetAll<CsOrderitem>() where
							t.OrderitemId == dtObj.OrderitemId	
								select t).FirstOrDefault();
			if (oaObj == null)
			{
				return CreateInternal(dtObj, context);
			}
			oaObj.Title = dtObj.Title;
			oaObj.OrderId = dtObj.OrderId;
			oaObj.Id = dtObj.Id;
			return oaObj;
		}
		
		public CsOrderitem UpdateOrCreate(CsOrderitemDto dtObj)
		{
			return UpdateOrCreateInternal(dtObj, this.Context);
		}
		
		public void Delete(CsOrderitemDto dtObj)
		{
			if(dtObj == null)
			{
				return;
			}
			CsOrderitem oaObj = (from t in this.Context.GetAll<CsOrderitem>() where
								t.OrderitemId == dtObj.OrderitemId	
								select t).FirstOrDefault();
			if (oaObj != null)
			{
				this.Context.Delete(oaObj);
			}
		}
		
		public void SaveChanges()
		{
			this.Context.SaveChanges();
		}
		
		public static CsOrderitemDto GetDto(CsOrderitem oaObj)
		{
			if(oaObj == null)
			{
				return null;
			}
			CsOrderitemDto dtObj = new CsOrderitemDto();
			dtObj.OrderitemId = oaObj.OrderitemId;
			dtObj.Title = oaObj.Title;
			dtObj.OrderId = oaObj.OrderId;
			dtObj.Id = oaObj.Id;
			
			return dtObj;
		}
		
		public static IList<CsOrderitemDto> GetDtos(IQueryable<CsOrderitem> oaObjects)
		{
			IList<CsOrderitemDto> dtObjects = new List<CsOrderitemDto>();
			foreach(CsOrderitem oaObj in oaObjects)
			{
				dtObjects.Add(GetDto(oaObj));
			}
			return dtObjects;
		}
		
		public void Dispose()
		{
			if(this.context != null)
			{
				this.context.Dispose();
			}
		}
	}
}
