#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using IseFrameworkUnitTest;

namespace IseFrameworkUnitTest	
{
	public partial class CsOrderitem
	{
		private long _orderitemid;
		public virtual long OrderitemId
		{
			get
			{
				return this._orderitemid;
			}
			set
			{
				this._orderitemid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private long? _orderid;
		public virtual long? OrderId
		{
			get
			{
				return this._orderid;
			}
			set
			{
				this._orderid = value;
			}
		}
		
		private long? _id;
		public virtual long? Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private CsOrder _csorder;
		public virtual CsOrder Csorder
		{
			get
			{
				return this._csorder;
			}
			set
			{
				this._csorder = value;
			}
		}
		
	}
}
#pragma warning restore 1591
